services:
  nginx: # Добавляем сервис nginx
    image: nginx:latest
    volumes:
      - /var/www/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Только для изменения default.conf
    ports:
      - '80:80'  # Открываем порт для статики
      - '443:443'  # Открываем порт для HTTPS
    networks:
      - backend

  postgres:
    image: postgres:15-alpine
    environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Пробрасываем порт 5432 наружу (для миграций, table plus)


  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - ./site_logs.log:/app/site_logs.log


networks:
  backend:
    driver: bridge

volumes:
  postgres_data: